#!/usr/bin/env bash

set -e pipefail

for arch in aarch64-linux-gnu arm-linux-gnueabihf powerpc64le-linux-gnu sparc64-linux-gnu
do
    cabal build --with-ghc="$arch"-ghc --with-ghc-pkg="$arch"-ghc-pkg --constraint='language-dickinson +cross' exe:emd
done
