#!/usr/bin/env bash

set -e pipefail
cabal build dickinson-bench --enable-profiling
$(fd dickinson-bench -t x -I) -- rename +RTS -p
ghc-prof-flamegraph dickinson-bench.prof
firefox dickinson-bench.svg
